site_name: RiceDocs
site_author: Anthony Rice
copyright: Copyright 2020 Anthony Rice

site_url: https://ajrice2.github.io/
site_description: 'Practicing with Github Pages and MkDocs'

theme:
  name: null
  custom_dir: 'cinder'
  colorscheme: github
  highlightjs: true

nav:
  - Home: index.md
  - Cinder:
      - Cinder Theme: cinderTheme.md
      - Cinder Markdown: cinderMD.md
  - Companies:
      - IT Companies: itCompanies.md
      - Science Companies: scienceCompanies.md
  - About:
      - About: about.md
      - Tony's Courses: tonyCourses.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true

shortcuts:
  help: 191    # ?
  next: 39     # right arrow
  previous: 37 # left arrow
  search: 83   # s

############################################################################

# extra_css:
#   - css/extra.css
#   - css/second_extra.css

# extra_javascript:
#   - js/extra.js

# docs_dir: docs/
# use_directory_urls: true

# plugins:
#   - search

############################################################################

## repo_name: ARice Github Repo
## repo_url: 'https://github.com/ajrice2/ajrice2.github.io'

############################################################################
# Configurations Not Used

# edit_uri
# google_analytics
# remote_branch
# remote_name
# strict
# dev_addr
